#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

alias vi='vim'
alias cls='clear'
alias h='fc -l'
alias j=jobs
alias m=$PAGER
alias ls='ls -G'
alias ll='ls -lhaFo'
alias l='ls -l'

export PATH=$HOME/local/bin:$PATH
export LD_LIBRARY_PATH=$HOME/local/lib:/usr/local/lib/mysql

export GIT_EDITOR=vim
export PYTHONDONTWRITEBYTECODE=x
export SVN_EDITOR=vim
export EDITOR=vim

[[ -s "${ZDOTDIR:-$HOME}/.autojump/etc/profile.d/autojump.sh" ]] && source "${ZDOTDIR:-$HOME}/.autojump/etc/profile.d/autojump.sh"

autoload -U compinit && compinit -u

#grep
export GREP_COLOR=33
export GREP_OPTIONS="--exclude=\*.svn\* --exclude=cscope.\* --exclude=\*.b --exclude=\*.o --color=auto --line-number"
